language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

before_script:
  - npm install
  - bash startGanache.sh

script:
  - truffle migrate --reset
  - npm run test

after_script:
  - bash stopGanache.sh
  - npm run coverage
  - cat coverage/lcov.info | coveralls
